# Generated by Django 4.1 on 2023-01-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.IntegerField()),
                ('emp_address', models.CharField(max_length=50)),
            ],
        ),
    ]
