# Generated by Django 4.1 on 2023-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_catagory_trending_remove_product_trending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-defauft,1-Trending'),
        ),
    ]
