# Generated by Django 4.1 on 2023-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_catagory_trending_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-defauft,1-Trending'),
        )
    ]