# Generated by Django 4.1 on 2023-02-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_catagory_trending_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]