# Generated by Django 4.1 on 2023-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_catagory_trending_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('4gp', '4gp'), ('6gp', '6gp'), ('8gp', '8gp')], default='4gp', max_length=3),
        ),
    ]
