# Generated by Django 4.1 on 2023-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_catagory_trending_remove_product_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.AddField(
            model_name='product',
            name='price_4gb',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_6gb',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_8gb',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_size',
            field=models.CharField(default='4GB', max_length=255),
        ),
    ]
