# Generated by Django 4.1 on 2023-03-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_remove_catagory_trending_remove_product_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ram_size',
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
